#!/usr/bin/env python3
# Emit golden_sample.h: the 544-word EPU input image (GLB words 0..543) as a C
# array, read from epu_fpga/glb_init.hex. The ESP32 sketch sends this over UART
# to validate the UART->EPU path against the known golden (class N, score 0x67).

from pathlib import Path

NWORDS = 544
HERE = Path(__file__).resolve().parent
GLB_HEX = HERE.parent.parent / "epu_fpga" / "glb_init.hex"
OUT = HERE / "golden_sample.h"

words = []
for line in GLB_HEX.read_text().splitlines():
    s = line.strip()
    if s:
        words.append(int(s, 16) & 0xFFFFFFFF)
    if len(words) == NWORDS:
        break

assert len(words) == NWORDS, f"expected {NWORDS} words, got {len(words)}"

lines = [
    "// Auto-generated by gen_golden_sample.py from epu_fpga/glb_init.hex",
    "// The 544-word EPU input image (GLB words 0..543). Expected result: class N, score 0x67.",
    "#pragma once",
    "#include <stdint.h>",
    f"#define GOLDEN_NWORDS {NWORDS}",
    "static const uint32_t GOLDEN_SAMPLE[GOLDEN_NWORDS] = {",
]
for i in range(0, NWORDS, 8):
    chunk = ", ".join(f"0x{w:08X}" for w in words[i:i+8])
    lines.append(f"    {chunk},")
lines.append("};")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({NWORDS} words)")
