#!/usr/bin/env python3
# gen_multiclass_header.py -- bundle the per-class 544-word tiled GLB input
# images into a single C header for the ESP32 multi-class demo sketch.
#
# Reads chip_fpga/demo_samples/in_{N,S,V,F}.dat (544 hex words each, produced by
# pack_glb_input.py) and writes samples.h with one uint32_t[544] array per class
# plus a small descriptor table (name, class index, expected score).
#
# Usage: python3 gen_multiclass_header.py <out_samples.h>

import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLES_DIR = os.path.normpath(os.path.join(HERE, "..", "demo_samples"))

# class -> (class index, expected uint8 score) -- from the bittrue golden model
# logits (argmax). Q omitted: too few training samples, model can't classify it.
CLASSES = [
    ("N", 0, 0x67),
    ("S", 1, 0x6B),
    ("V", 2, 0x65),
    ("F", 3, 0x8A),
]

def read_words(path):
    w = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                w.append(int(line, 16) & 0xFFFFFFFF)
    assert len(w) == 544, f"{path}: expected 544 words, got {len(w)}"
    return w

def main():
    if len(sys.argv) != 2:
        print("usage: gen_multiclass_header.py <out_samples.h>", file=sys.stderr)
        sys.exit(2)
    out = sys.argv[1]
    lines = []
    lines.append("// Auto-generated by gen_multiclass_header.py")
    lines.append("// Per-class 544-word EPU input images (GLB words 0..543), tiled layout.")
    lines.append("// Source: MIT-BIH test_clean samples -> extract_mitdb_one_case_layer_io.py")
    lines.append("//         -> pack_glb_input.py (3 ECG/word @ stride 4, zp pad 0x31/0x7F).")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#define SAMPLE_NWORDS 544")
    lines.append("")
    arrays = {}
    for name, cls, score in CLASSES:
        words = read_words(os.path.join(SAMPLES_DIR, f"in_{name}.dat"))
        arrays[name] = words
        lines.append(f"// class {name}: expected class index {cls}, score 0x{score:02X}")
        lines.append(f"static const uint32_t SAMPLE_{name}[SAMPLE_NWORDS] = {{")
        for i in range(0, 544, 8):
            row = ", ".join(f"0x{x:08X}" for x in words[i:i+8])
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")
    # descriptor table
    lines.append("typedef struct {")
    lines.append("    char            key;       // serial char to select")
    lines.append("    const char     *name;      // class name")
    lines.append("    uint8_t         cls;        // expected class index")
    lines.append("    uint8_t         score;      // expected uint8 score")
    lines.append("    const uint32_t *words;      // 544-word image")
    lines.append("} sample_desc_t;")
    lines.append("")
    lines.append("static const sample_desc_t SAMPLES[] = {")
    for name, cls, score in CLASSES:
        key = name.lower()
        lines.append(f'    {{ \'{key}\', "{name}", {cls}, 0x{score:02X}, SAMPLE_{name} }},')
    lines.append("};")
    lines.append(f"#define NUM_SAMPLES {len(CLASSES)}")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} with {len(CLASSES)} samples: {', '.join(n for n,_,_ in CLASSES)}")

if __name__ == "__main__":
    main()
